import type { DailyBrief } from "./types";

const demoDate = new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Shanghai" });
const demoGeneratedAt = new Date().toISOString();
const demoTimestamp = (time: string) => new Date(`${demoDate}T${time}:00+08:00`).toISOString();

export const demoBrief: DailyBrief = {
  date: demoDate,
  generatedAt: demoGeneratedAt,
  mode: "demo",
  aiEnabled: false,
  translationEnabled: true,
  stats: { candidates: 186, consolidatedEvents: 34, topStories: 5, sourcesOnline: 12 },
  headlines: [
    {
      id: "nvda-capex",
      rank: 1,
      ticker: "NVDA",
      title: "大型云端客户的 AI 资本支出，仍是今日风险偏好的核心变数",
      summary: "市场讨论集中在 AI 伺服器需求、供应节奏与客户资本支出延续性。正式交易前，应优先确认公司公告与主流媒体是否出现一致讯号。",
      publishedAt: demoTimestamp("06:45"),
      newsTimeSource: "Google News",
      timestampKind: "published",
      keyPoints: ["大型云端客户的 AI 资本支出，是目前需求能见度的主要领先指标。", "观察 Blackwell 交付节奏、供应限制与资料中心客户的订单延续性。", "正式结论必须由公司公告及主流财经媒体交叉确认。"],
      marketImpact: "若需求能见度提高，半导体与资料中心供应链可能同步受益；若交付或毛利预期转弱，估值较高标的波动会先放大。",
      category: "AI",
      impact: 5,
      confidence: 92,
      mentions: 48,
      sentiment: "positive",
      sources: [
        { name: "Google News", type: "News", url: "https://news.google.com/" },
        { name: "r/stocks", type: "Reddit", url: "https://www.reddit.com/r/stocks/" },
        { name: "X discovery", type: "X", url: "https://x.com/search?q=NVDA" },
      ],
    },
    {
      id: "fomc-rates",
      rank: 2,
      ticker: "FOMC",
      title: "利率路径重新定价，市场等待下一个能改变共识的官方讯号",
      summary: "短线焦点从单一数据转向联准会措辞、就业与通膨资料的组合。社群押注仅作为情绪指标，仍以官方发布为事实基准。",
      publishedAt: demoTimestamp("05:30"),
      newsTimeSource: "Federal Reserve",
      timestampKind: "published",
      keyPoints: ["市场正同时评估通膨、就业与联准会措辞，而非只看单一数据。", "美债殖利率与降息机率的变化，是成长股估值的重要传导渠道。", "政策判读以联准会正式文件及官员谈话为准。"],
      marketImpact: "殖利率若上行，成长股估值承压；若降息预期提前，科技股、长天期债券与高风险资产可能获得支撑。",
      category: "Macro",
      impact: 5,
      confidence: 95,
      mentions: 36,
      sentiment: "neutral",
      sources: [
        { name: "Federal Reserve", type: "Official", url: "https://www.federalreserve.gov/newsevents.htm" },
        { name: "Google News", type: "News", url: "https://news.google.com/" },
      ],
    },
    {
      id: "tsmc-capacity",
      rank: 3,
      ticker: "TSM",
      title: "先进制程与先进封装供应，持续牵动 AI 供应链评价",
      summary: "投资人关注产能扩张速度、客户组合与资本支出效率。真正有交易价值的讯号，应由法说、月营收或公司公告交叉确认。",
      publishedAt: demoTimestamp("04:20"),
      newsTimeSource: "Company IR",
      timestampKind: "published",
      keyPoints: ["先进制程及先进封装产能，是 AI 晶片出货能否扩大的关键限制。", "追踪客户组合、资本支出效率与产能扩张速度。", "月营收、法说会和公司公告是主要验证来源。"],
      marketImpact: "供给瓶颈舒缓有利下游客户放量，但也可能改变稀缺性溢价；设备、材料与封装族群将出现不同敏感度。",
      category: "Semiconductor",
      impact: 4,
      confidence: 88,
      mentions: 31,
      sentiment: "positive",
      sources: [
        { name: "Company IR", type: "Official", url: "https://investor.tsmc.com/english" },
        { name: "r/investing", type: "Reddit", url: "https://www.reddit.com/r/investing/" },
      ],
    },
    {
      id: "ai-model-cycle",
      rank: 4,
      ticker: "AI",
      title: "模型更新与企业导入速度，取代单纯参数竞赛成为焦点",
      summary: "讨论重心逐渐转向推理成本、企业工作流程整合与实际付费转换。未证实的功能截图或匿名爆料不列入主要结论。",
      publishedAt: demoTimestamp("03:10"),
      newsTimeSource: "Company blogs",
      timestampKind: "published",
      keyPoints: ["市场焦点由模型参数转向推理成本、企业导入及付费转换。", "通路、产品体验及工作流程整合将影响模型公司的商业化能力。", "匿名爆料与未验证截图不列入主要事实。"],
      marketImpact: "企业采用加速将利好云端、资料与应用层；成本下降则可能压缩基础模型差异化，让竞争转向通路与产品体验。",
      category: "AI",
      impact: 4,
      confidence: 82,
      mentions: 29,
      sentiment: "positive",
      sources: [
        { name: "Company blogs", type: "Official", url: "https://openai.com/news/" },
        { name: "r/MachineLearning", type: "Reddit", url: "https://www.reddit.com/r/MachineLearning/" },
      ],
    },
    {
      id: "crypto-flows",
      rank: 5,
      ticker: "BTC",
      title: "ETF 资金流与宏观风险偏好，主导加密资产短线方向",
      summary: "价格讨论热度上升，但单一帐号或匿名贴文不构成投资证据。日报将资金流、监管公告与市场情绪分开呈现。",
      publishedAt: demoTimestamp("02:40"),
      newsTimeSource: "SEC",
      timestampKind: "published",
      keyPoints: ["ETF 资金流与宏观风险偏好共同主导短线价格方向。", "监管公告、资金流与社群情绪会分开判读。", "单一帐号或匿名贴文只视为早期讯号。"],
      marketImpact: "持续流入可支撑相关资产与交易平台；若风险偏好反转，高杠杆部位可能放大价格波动。",
      category: "Crypto",
      impact: 3,
      confidence: 78,
      mentions: 24,
      sentiment: "neutral",
      sources: [
        { name: "SEC", type: "Official", url: "https://www.sec.gov/newsroom" },
        { name: "Google News", type: "News", url: "https://news.google.com/" },
      ],
    },
  ],
  marketHeat: [
    { category: "AI", score: 5, direction: "up", note: "需求与产品更新同步升温" },
    { category: "Semiconductor", score: 4, direction: "up", note: "产能与供应链能见度" },
    { category: "Macro", score: 4, direction: "flat", note: "等待利率路径新讯号" },
    { category: "Crypto", score: 3, direction: "flat", note: "资金流与情绪拉锯" },
    { category: "Geopolitics", score: 2, direction: "down", note: "目前缺乏跨来源确认" },
  ],
  socialBuzz: {
    reddit: [
      {
        id: "demo-reddit-nvda",
        label: "英伟达 / 人工智能资本支出",
        description: "投资社区正在讨论大型云端客户的资本支出能否继续支撑 Blackwell 需求与数据中心订单。",
        url: "https://www.reddit.com/r/stocks/search/?q=NVDA&restrict_sr=1&sort=hot",
        source: "r/stocks",
        platform: "Reddit",
        publishedAt: demoTimestamp("04:18"),
        timestampKind: "published",
        category: "AI",
        signalScore: 91,
        metricKind: "engagement",
        relatedHeadlineId: "nvda-capex",
        relationKind: "semantic",
        mentions: 48,
        change: 0,
        sentiment: "positive",
      },
      {
        id: "demo-reddit-tsm",
        label: "台积电先进制程产能",
        description: "讨论焦点集中在先进制程、先进封装与 AI 芯片供应链的产能限制。",
        url: "https://www.reddit.com/r/investing/search/?q=TSMC&restrict_sr=1&sort=hot",
        source: "r/investing",
        platform: "Reddit",
        publishedAt: demoTimestamp("03:42"),
        timestampKind: "published",
        category: "Semiconductor",
        signalScore: 78,
        metricKind: "engagement",
        relatedHeadlineId: "tsmc-capacity",
        relationKind: "semantic",
        mentions: 31,
        change: 0,
        sentiment: "positive",
      },
      {
        id: "demo-reddit-ai-valuation",
        label: "人工智能估值是否过热",
        description: "部分讨论质疑高估值能否被未来营收与利润增长消化，目前仍属于观点与情绪信号。",
        url: "https://www.reddit.com/r/SecurityAnalysis/search/?q=AI%20valuation&restrict_sr=1&sort=hot",
        source: "r/SecurityAnalysis",
        platform: "Reddit",
        publishedAt: demoTimestamp("02:56"),
        timestampKind: "published",
        category: "AI",
        signalScore: 67,
        metricKind: "engagement",
        mentions: 26,
        change: 0,
        sentiment: "negative",
      },
    ],
    x: [
      {
        id: "demo-x-fomc",
        label: "FOMC 利率路径",
        description: "市场账号集中解读通胀、就业与美联储措辞对降息概率和美债收益率的影响。",
        url: "https://x.com/search?q=FOMC&src=typed_query&f=live",
        source: "X · FOMC 搜索",
        platform: "X",
        publishedAt: demoTimestamp("04:02"),
        timestampKind: "collected",
        category: "Macro",
        signalScore: 86,
        metricKind: "engagement",
        relatedHeadlineId: "fomc-rates",
        relationKind: "semantic",
        mentions: 36,
        change: 0,
        sentiment: "neutral",
      },
      {
        id: "demo-x-ai-model",
        label: "人工智能模型产品更新",
        description: "产品发布与企业采用相关讨论升温，仍需回到公司公告确认功能、价格与可用范围。",
        url: "https://x.com/search?q=OpenAI%20model&src=typed_query&f=live",
        source: "X · OpenAI 搜索",
        platform: "X",
        publishedAt: demoTimestamp("03:24"),
        timestampKind: "collected",
        category: "AI",
        signalScore: 74,
        metricKind: "engagement",
        relatedHeadlineId: "ai-model-cycle",
        relationKind: "semantic",
        mentions: 29,
        change: 0,
        sentiment: "positive",
      },
      {
        id: "demo-x-etf-flows",
        label: "ETF 资金流",
        description: "社交讨论关注资金净流入是否延续，但平台热度本身不能替代正式资金流数据。",
        url: "https://x.com/search?q=ETF%20flows&src=typed_query&f=live",
        source: "X · ETF 搜索",
        platform: "X",
        publishedAt: demoTimestamp("02:38"),
        timestampKind: "collected",
        category: "ETF",
        signalScore: 59,
        metricKind: "engagement",
        relatedHeadlineId: "crypto-flows",
        relationKind: "semantic",
        mentions: 24,
        change: 0,
        sentiment: "neutral",
      },
    ],
  },
  watchlist: [
    { time: "美东时间 08:30", event: "美国重要经济数据", why: "可能改变利率预期与收益率曲线", category: "Macro" },
    { time: "盘前", event: "大型科技公司公告", why: "确认 AI 资本支出与需求讯号", category: "AI" },
    { time: "盘后", event: "半导体供应链更新", why: "观察先进制程、封装与设备订单", category: "Semiconductor" },
  ],
};
