import type { DailyBrief } from "./types";

export const demoBrief: DailyBrief = {
  date: "2026-07-14",
  generatedAt: "2026-07-14T07:30:00+08:00",
  mode: "demo",
  aiEnabled: false,
  stats: { candidates: 186, consolidatedEvents: 34, topStories: 5, sourcesOnline: 12 },
  headlines: [
    {
      id: "nvda-capex",
      rank: 1,
      ticker: "NVDA",
      title: "大型雲端客戶的 AI 資本支出，仍是今日風險偏好的核心變數",
      summary: "市場討論集中在 AI 伺服器需求、供應節奏與客戶資本支出延續性。正式交易前，應優先確認公司公告與主流媒體是否出現一致訊號。",
      marketImpact: "若需求能見度提高，半導體與資料中心供應鏈可能同步受益；若交付或毛利預期轉弱，估值較高標的波動會先放大。",
      category: "AI",
      impact: 5,
      confidence: 92,
      mentions: 48,
      sentiment: "positive",
      sources: [
        { name: "Google News", type: "News", url: "https://news.google.com/" },
        { name: "r/stocks", type: "Reddit", url: "https://www.reddit.com/r/stocks/" },
        { name: "X discovery", type: "X", url: "https://x.com/search?q=NVDA" },
      ],
    },
    {
      id: "fomc-rates",
      rank: 2,
      ticker: "FOMC",
      title: "利率路徑重新定價，市場等待下一個能改變共識的官方訊號",
      summary: "短線焦點從單一數據轉向聯準會措辭、就業與通膨資料的組合。社群押注僅作為情緒指標，仍以官方發布為事實基準。",
      marketImpact: "殖利率若上行，成長股估值承壓；若降息預期提前，科技股、長天期債券與高風險資產可能獲得支撐。",
      category: "Macro",
      impact: 5,
      confidence: 95,
      mentions: 36,
      sentiment: "neutral",
      sources: [
        { name: "Federal Reserve", type: "Official", url: "https://www.federalreserve.gov/newsevents.htm" },
        { name: "Google News", type: "News", url: "https://news.google.com/" },
      ],
    },
    {
      id: "tsmc-capacity",
      rank: 3,
      ticker: "TSM",
      title: "先進製程與先進封裝供應，持續牽動 AI 供應鏈評價",
      summary: "投資人關注產能擴張速度、客戶組合與資本支出效率。真正有交易價值的訊號，應由法說、月營收或公司公告交叉確認。",
      marketImpact: "供給瓶頸舒緩有利下游客戶放量，但也可能改變稀缺性溢價；設備、材料與封裝族群將出現不同敏感度。",
      category: "Semiconductor",
      impact: 4,
      confidence: 88,
      mentions: 31,
      sentiment: "positive",
      sources: [
        { name: "Company IR", type: "Official", url: "https://investor.tsmc.com/english" },
        { name: "r/investing", type: "Reddit", url: "https://www.reddit.com/r/investing/" },
      ],
    },
    {
      id: "ai-model-cycle",
      rank: 4,
      ticker: "AI",
      title: "模型更新與企業導入速度，取代單純參數競賽成為焦點",
      summary: "討論重心逐漸轉向推理成本、企業工作流程整合與實際付費轉換。未證實的功能截圖或匿名爆料不列入主要結論。",
      marketImpact: "企業採用加速將利好雲端、資料與應用層；成本下降則可能壓縮基礎模型差異化，讓競爭轉向通路與產品體驗。",
      category: "AI",
      impact: 4,
      confidence: 82,
      mentions: 29,
      sentiment: "positive",
      sources: [
        { name: "Company blogs", type: "Official", url: "https://openai.com/news/" },
        { name: "r/MachineLearning", type: "Reddit", url: "https://www.reddit.com/r/MachineLearning/" },
      ],
    },
    {
      id: "crypto-flows",
      rank: 5,
      ticker: "BTC",
      title: "ETF 資金流與宏觀風險偏好，主導加密資產短線方向",
      summary: "價格討論熱度上升，但單一帳號或匿名貼文不構成投資證據。日報將資金流、監管公告與市場情緒分開呈現。",
      marketImpact: "持續流入可支撐相關資產與交易平台；若風險偏好反轉，高槓桿部位可能放大價格波動。",
      category: "Crypto",
      impact: 3,
      confidence: 78,
      mentions: 24,
      sentiment: "neutral",
      sources: [
        { name: "SEC", type: "Official", url: "https://www.sec.gov/newsroom" },
        { name: "Google News", type: "News", url: "https://news.google.com/" },
      ],
    },
  ],
  marketHeat: [
    { category: "AI", score: 5, direction: "up", note: "需求與產品更新同步升溫" },
    { category: "Semiconductor", score: 4, direction: "up", note: "產能與供應鏈能見度" },
    { category: "Macro", score: 4, direction: "flat", note: "等待利率路徑新訊號" },
    { category: "Crypto", score: 3, direction: "flat", note: "資金流與情緒拉鋸" },
    { category: "Geopolitics", score: 2, direction: "down", note: "目前缺乏跨來源確認" },
  ],
  socialBuzz: {
    reddit: [
      { label: "NVDA / AI capex", mentions: 48, change: 32, sentiment: "positive" },
      { label: "TSMC capacity", mentions: 31, change: 18, sentiment: "positive" },
      { label: "AI valuation", mentions: 26, change: 11, sentiment: "negative" },
    ],
    x: [
      { label: "FOMC rate path", mentions: 36, change: 27, sentiment: "neutral" },
      { label: "Model releases", mentions: 29, change: 21, sentiment: "positive" },
      { label: "ETF flows", mentions: 24, change: -6, sentiment: "neutral" },
    ],
  },
  watchlist: [
    { time: "08:30 ET", event: "美國重要經濟數據", why: "可能改變利率預期與殖利率曲線", category: "Macro" },
    { time: "盤前", event: "大型科技公司公告", why: "確認 AI 資本支出與需求訊號", category: "AI" },
    { time: "盤後", event: "半導體供應鏈更新", why: "觀察先進製程、封裝與設備訂單", category: "Semiconductor" },
  ],
};
