import { validateHeadlineEvidence } from "./source-evidence";
import type { DailyBrief, Headline, HeadlineClaim } from "./types";

export interface PublicationEvidenceIssue {
  headlineId: string;
  headlineRank: number;
  claimKey: string;
  reason: string;
  code:
    | "SOURCE_MISSING"
    | "SOURCE_VERSION_MISSING"
    | "SOURCE_EVIDENCE_VERSION_MISSING"
    | "CLAIM_MISSING"
    | "CLAIM_UNEXPECTED"
    | "CLAIM_DUPLICATE"
    | "CLAIM_DISPLAY_MISMATCH"
    | "CLAIM_TYPE_MISMATCH"
    | "CLAIM_ORDINAL_MISMATCH"
    | "CLAIM_PENDING"
    | "CITATION_MISSING"
    | "CITATION_VERSION_MISSING"
    | "TRANSLATION_INCOMPLETE"
    | "EVIDENCE_INVALID";
}

function issue(headline: Headline, claimKey: string, code: PublicationEvidenceIssue["code"], reason: string): PublicationEvidenceIssue {
  return { headlineId: headline.id, headlineRank: headline.rank, claimKey, code, reason };
}

function nonEmptyText(value: unknown): value is string {
  return typeof value === "string" && Boolean(value.trim());
}

function requiredClaims(
  headline: Headline,
  keyPoints: string[],
): Array<{ claimKey: string; type: HeadlineClaim["type"]; ordinal: number; statement: string }> {
  const required: Array<{ claimKey: string; type: HeadlineClaim["type"]; ordinal: number; statement: string }> = [
    { claimKey: "title", type: "title", ordinal: 0, statement: headline.title },
    { claimKey: "summary", type: "summary", ordinal: 1, statement: headline.summary },
    ...keyPoints.map((statement, index) => ({
      claimKey: `important_information:${index}`,
      type: "important_information" as const,
      ordinal: index + 2,
      statement,
    })),
    { claimKey: "market_impact", type: "market_impact", ordinal: keyPoints.length + 2, statement: headline.marketImpact },
  ];
  const hasDirectionalJudgment = headline.marketDirection === "bullish"
    || headline.marketDirection === "bearish"
    || headline.marketDirection === "mixed"
    || nonEmptyText(headline.directionRationale);
  if (hasDirectionalJudgment || headline.impact >= 4 || (headline.directionConfidence ?? 0) >= 70) {
    required.push({
      claimKey: "direction_rationale",
      type: "direction_rationale",
      ordinal: keyPoints.length + 3,
      statement: headline.directionRationale ?? "",
    });
  }
  return required;
}

function isManagedPageClaim(claimKey: string): boolean {
  return claimKey === "title"
    || claimKey === "summary"
    || claimKey === "market_impact"
    || claimKey === "direction_rationale"
    || /^important_information:\d+$/.test(claimKey);
}

function claimIssues(
  headline: Headline,
  claim: HeadlineClaim | undefined,
  expected: { claimKey: string; type: HeadlineClaim["type"]; ordinal: number; statement: string },
): PublicationEvidenceIssue[] {
  const claimKey = expected.claimKey;
  if (!claim) return [issue(headline, claimKey, "CLAIM_MISSING", "该判断没有结构化证据记录")];
  if (claim.type !== expected.type) {
    return [issue(headline, claimKey, "CLAIM_TYPE_MISMATCH", "声明类型与页面字段不一致")];
  }
  if (claim.ordinal !== expected.ordinal) {
    return [issue(headline, claimKey, "CLAIM_ORDINAL_MISMATCH", "声明顺序与页面字段顺序不一致")];
  }
  if (!nonEmptyText(expected.statement) || claim.statement !== expected.statement) {
    return [issue(headline, claimKey, "CLAIM_DISPLAY_MISMATCH", "页面显示内容与已引用的声明不一致")];
  }
  if (claim.verificationStatus === "pending_confirmation" || claim.verificationStatus === "legacy_unverified") {
    return [issue(headline, claimKey, "CLAIM_PENDING", "该判断仍为待确认，不能作为已验证事实发布")];
  }
  if (!Array.isArray(claim.citations)) {
    return [issue(headline, claimKey, "EVIDENCE_INVALID", "声明引用格式无效")];
  }
  const availableSupport = claim.citations.some((citation) => citation?.relation === "supports"
    && citation.confidence > 0
    && citation.locatorStatus !== "unavailable"
    && citation.directness !== "unavailable");
  if (!availableSupport) return [issue(headline, claimKey, "CITATION_MISSING", "该判断没有可用且真正支持它的原始证据")];
  if (claim.citations.some((citation) => !nonEmptyText(citation?.versionId)
    || !nonEmptyText(citation?.sourceDocumentVersionId))) {
    return [issue(headline, claimKey, "CITATION_VERSION_MISSING", "引用未绑定精确来源版本或证据版本")];
  }
  return [];
}

/** Strict publication gate for drafts generated by the auditable pipeline. */
export function publicationEvidenceIssues(brief: DailyBrief): PublicationEvidenceIssue[] {
  return brief.headlines.flatMap((headline) => {
    const issues: PublicationEvidenceIssue[] = [];
    if (brief.translationEnabled !== true) {
      issues.push(issue(
        headline,
        "translation",
        "TRANSLATION_INCOMPLETE",
        "简体中文自动翻译尚未完整完成，必须先保存严格翻译后的审核快照",
      ));
    }
    const sources = Array.isArray(headline.sources) ? headline.sources : [];
    if (!sources.length) {
      issues.push(issue(headline, "source", "SOURCE_MISSING", "事件没有任何可核对的来源"));
    }
    if (!Array.isArray(headline.sources)
      || sources.some((source) => !nonEmptyText(source?.sourceDocumentId)
        || !nonEmptyText(source?.sourceDocumentVersionId))) {
      issues.push(issue(headline, "source", "SOURCE_VERSION_MISSING", "来源没有绑定精确的不可变版本"));
    }
    sources.forEach((source, sourceIndex) => {
      if (source.evidence !== undefined && !Array.isArray(source.evidence)) {
        issues.push(issue(headline, `source:${sourceIndex}`, "EVIDENCE_INVALID", "来源证据清单格式无效"));
        return;
      }
      if ((source.evidence ?? []).some((evidence) => !nonEmptyText(evidence?.versionId)
        || !nonEmptyText(evidence?.sourceDocumentVersionId))) {
        issues.push(issue(
          headline,
          `source:${sourceIndex}`,
          "SOURCE_EVIDENCE_VERSION_MISSING",
          "来源证据没有绑定精确的证据版本或来源版本",
        ));
      }
    });

    const claimList = Array.isArray(headline.claims) ? headline.claims : [];
    if (headline.claims !== undefined && !Array.isArray(headline.claims)) {
      issues.push(issue(headline, "claims", "EVIDENCE_INVALID", "结构化声明清单格式无效"));
    }
    claimList.forEach((claim) => {
      if (!claim || typeof claim !== "object") {
        issues.push(issue(headline, "claim", "EVIDENCE_INVALID", "结构化声明格式无效"));
        return;
      }
      if (claim.verificationStatus === "pending_confirmation" || claim.verificationStatus === "legacy_unverified") {
        issues.push(issue(headline, claim.claimKey || "claim", "CLAIM_PENDING", "该判断仍为待确认，不能发布"));
      }
      if (!Array.isArray(claim.citations)) {
        issues.push(issue(headline, claim.claimKey || "claim", "EVIDENCE_INVALID", "声明引用格式无效"));
      } else if (claim.citations.some((citation) => !nonEmptyText(citation?.versionId)
        || !nonEmptyText(citation?.sourceDocumentVersionId))) {
        issues.push(issue(
          headline,
          claim.claimKey || "claim",
          "CITATION_VERSION_MISSING",
          "所有声明引用都必须绑定精确来源版本与证据版本",
        ));
      }
    });
    const duplicateKeys = claimList
      .filter((claim): claim is HeadlineClaim => Boolean(claim && typeof claim === "object"))
      .map((claim) => claim.claimKey)
      .filter((key, index, all) => all.indexOf(key) !== index);
    for (const key of new Set(duplicateKeys)) {
      issues.push(issue(headline, key, "CLAIM_DUPLICATE", "同一页面字段存在多个声明记录"));
    }
    const claims = new Map(claimList
      .filter((claim): claim is HeadlineClaim => Boolean(claim && typeof claim === "object"))
      .map((claim) => [claim.claimKey, claim]));
    const keyPoints = Array.isArray(headline.keyPoints) ? headline.keyPoints : [];
    if (headline.keyPoints !== undefined
      && (!Array.isArray(headline.keyPoints) || headline.keyPoints.some((point) => !nonEmptyText(point)))) {
      issues.push(issue(headline, "important_information", "EVIDENCE_INVALID", "重要信息字段格式无效或包含空白项目"));
    }
    const expectedClaims = requiredClaims(headline, keyPoints);
    const expectedKeys = new Set(expectedClaims.map((item) => item.claimKey));
    for (const claim of claimList) {
      if (claim && typeof claim === "object"
        && isManagedPageClaim(claim.claimKey)
        && !expectedKeys.has(claim.claimKey)) {
        issues.push(issue(
          headline,
          claim.claimKey,
          "CLAIM_UNEXPECTED",
          "声明已不对应任何页面字段，必须建立新事件版本移除旧引用",
        ));
      }
    }
    for (const expected of expectedClaims) {
      issues.push(...claimIssues(headline, claims.get(expected.claimKey), expected));
    }
    try {
      const integrity = validateHeadlineEvidence(headline);
      for (const invalid of integrity.issues) {
        issues.push(issue(headline, invalid.claimId ?? "evidence", "EVIDENCE_INVALID", `${invalid.code}: ${invalid.message}`));
      }
    } catch (error) {
      issues.push(issue(
        headline,
        "evidence",
        "EVIDENCE_INVALID",
        error instanceof Error ? error.message : "证据结构无法验证",
      ));
    }
    const seen = new Set<string>();
    return issues.filter((item) => {
      const key = `${item.claimKey}:${item.code}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  });
}
